DROP TABLE IF EXISTS admin_acc;
DROP TABLE IF EXISTS stdLess;
DROP TABLE IF EXISTS stdLessHyst;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS lesson;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS professor;
DROP TABLE IF EXISTS company;

DROP DATABASE IF EXISTS training_center